name: Validate 'setup-xcode'
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  versions-macOS-14:
    name: macOS 14
    runs-on: macos-14
    strategy:
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode
        xcode-version: ['15.0.1', '15.1', '15.2', '15.3', '15.4', '16.1', '16.2', latest, latest-stable]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: ./
        name: Setup Xcode
        id: setup-xcode
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Print output variables
        run: |
          echo "Version: ${{ steps.setup-xcode.outputs.version }}"
          echo "Path: ${{ steps.setup-xcode.outputs.path }}"

  versions-macOS-26:
    name: macOS 26
    runs-on: macos-26
    strategy:
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md#xcode
        xcode-version: ['26.0.1', '26.1.1', '26.2', '26.3', latest, latest-stable]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: ./
        name: Setup Xcode
        id: setup-xcode
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Print output variables
        run: |
          echo "Version: ${{ steps.setup-xcode.outputs.version }}"
          echo "Path: ${{ steps.setup-xcode.outputs.path }}"

  versions-macOS-15:
    name: macOS 15
    runs-on: macos-15
    strategy:
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#xcode
        xcode-version: ['16.0', '16.1', '16.4', '26.0.1', '26.3', latest, latest-stable]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: ./
        name: Setup Xcode
        id: setup-xcode
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Print output variables
        run: |
          echo "Version: ${{ steps.setup-xcode.outputs.version }}"
          echo "Path: ${{ steps.setup-xcode.outputs.path }}"
